version: '3.8'
services:
    mysql:
        hostname: mysql
        image: mysql:8
        container_name: mysql
        environment:
        - MYSQL_ROOT_PASSWORD=
        - MYSQL_DATABASE=fcmdb
        ports:
        - 3306:3306
        - 33060:33060
        networks:
        - connection1
    fcm:
        hostname: fcm
        build: .
        image: foodcaloriemeter:1.0
        container_name: fcm
        environment:
        - FDC_KEY=
        - FDC_URL=
        - JWT_CKEY=
        - MM_KEY=
        - DB_USER=
        - DB_PASS=
        - DB_HOST=
        - HOST=
        - PORT=
        - SPRING_PROFILES_ACTIVE=prod
        ports:
        - xxxx:xxxx
        networks:
        - connection1
        depends_on:
        - mysql
networks:
    connection1:
        name: connection1
        driver: bridge