debug: true
server:
   port: 9682
   host: localhost
spring:
   datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:fcmdb
      username: sa
      password:
   jpa:
      hibernate:
         ddl-auto: create
      defer-datasource-initialization: true
      properties:
         hibernate:
            show_sql: false
            format_sql: true
   main:
      allow-bean-definition-overriding: true
   h2:
      console:
         enabled: true
         path: /h2
   mvc:
      pathmatch:
         matching-strategy: ant_path_matcher
jwt:
   token: ${JWT_CKEY}