debug: false
server:
   port: ${PORT}
   host: ${HOST}
spring:
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${DB_HOST}/fcmdb
      username: root
      password: ${DB_PASS}
   jpa:
      hibernate:
         ddl-auto: update
      defer-datasource-initialization: true
      properties:
         hibernate:
            show_sql: false
            format_sql: true    
   h2:
      console:
         enabled: true
         path: /h2
   mvc:
      pathmatch:
         matching-strategy: ant_path_matcher
Translation:
   key: ${MM_KEY}
   host: ${MM_HOST}
   url: https://${MM_HOST}
fdc:
   key: ${FDC_KEY}
   url: ${FDC_URL}
jwt:
   token: ${JWT_CKEY}
   