debug: true
server:
   port: 9682
   host: localhost
spring:
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/fcmdb
      username: root
      password: root
   jpa:
      hibernate:
         ddl-auto: update
      defer-datasource-initialization: true
      properties:
         hibernate:
            show_sql: true
            format_sql: true
   h2:
      console:
         enabled: true
         path: /h2
   mvc:
      pathmatch:
         matching-strategy: ant_path_matcher
translation:
   key: ${MM_KEY}
   host: ${MM_HOST}
   url: https://${MM_HOST}
fdc:
   key: ${FDC_KEY}
   url: ${FDC_URL}
jwt:
   token: ${JWT_CKEY}